version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck
    - depguard
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocognit
    - gocyclo
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - godox
    - gosmopolitan
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - mirror
    - mnd
    - musttag
    - nestif
    - nilerr
    - nilnil
    - noctx
    - noinlineerr
    - nlreturn
    - nonamedreturns
    - revive
    - tagliatelle
    - unparam
    - usestdlibvars
    - wrapcheck
    - wsl_v5
    - wsl

  settings:
    staticcheck:
      checks:
        - all
        - -ST1005
        - -QF1012

run:
  timeout: 5m
